### ISSUE TITLE
network supabase declared as external, but could not be found

### ISSUE THREAD

**Issue by MrVibe** [supabase-community/supabase-traefik#4]
While following the instructions when trying to up the traefik docker, I get this error:

network supabase declared as external, but could not be found

While trying to up the supabase docker image:

validating /supabase/docker/docker-compose.yml: networks must be a mapping

kindly suggest what I may be missing here.

**Comment by NorkzYT** [comment]
@MrVibe 

Good day mate,

Hope you are doing well.

The solution to this issue is to run `docker network create supabase` before composing up the docker compose file.
To advise, this guide assumes that the user knows basic knowledge of Docker.

If the instructions above resolve your issue then please do close this issue.
